// ********RoostGPT********
/*
Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o-standard

playwright test generated for endpoint: /store/order/{orderId}, with method: get
RoostTestHash={
  "paramDesc": {
    "orderId": "integer"
  },
  "headerDesc": {},
  "reqBodyDesc": {},
  "resBodyDesc": {
    "200": "{\n  \"id\": \"integer\",\n  \"petId\": \"integer\",\n  \"quantity\": \"integer\",\n  \"shipDate\": \"string\",\n  \"status\": \"enum: placed, approved, delivered\"\n}",
    "400": "Invalid ID supplied with empty response body",
    "404": "Order not found with empty response body"
  }
}

*/

// ********RoostGPT********

import test, { expect, request } from "@playwright/test";
import { readCsvData } from "./utility.js";

test("Find purchase order by ID", async () => {
  const baseURL =  "https://petstore.swagger.io/v2";
  const context = await request.newContext({
    baseURL,
    extraHTTPHeaders: {
      "Content-Type": "application/json",
    },
  });

  const csvFilePath = `/var/tmp/Roost/RoostGPT/roost_test/1732294427/source/my-products/playwrightApiTests/tests/Find_purchase_order_by_ID.csv`
  const testData = await readCsvData(csvFilePath);

  for (let i = 0; i < testData.length; i++) {
    const csvDataRow = testData[i];
    const { statusCode, ...sampleData } = csvDataRow;

    const response = await context.get(`/store/order/${sampleData.orderId}`);
    expect(response.status()).toBe(statusCode);

    if (response.status() === statusCode) {
      console.log("Response for getOrderById is:", await response.json());
    }
  }
})