// ********RoostGPT********
/*
Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o-standard

playwright test generated for endpoint: /user/login, with method: get
RoostTestHash=/user/login-get-665e6cee9d

*/

// ********RoostGPT********

import test, { expect, request } from "@playwright/test";
test("Logs user into the system", async () => {
  const baseURL =  "https://petstore.swagger.io/v2";
  const context = await request.newContext({
    baseURL,
    extraHTTPHeaders: {
      "Content-Type": "application/json",
    },
  });

  const response = await context.get("/user/login");
  
  if (response.status() === 200) {
    expect(response.status()).toBe(200);
    console.log("Response for loginUser is:", await response.json());
  }
  
  if (response.status() === 400) {
    expect(response.status()).toBe(400);
    console.log("Response for loginUser is:", await response.json());
  }
})