// ********RoostGPT********
/*
Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o-standard

playwright test generated for endpoint: /user/logout, with method: get
RoostTestHash={
  "paramDesc": {},
  "headerDesc": {},
  "reqBodyDesc": {},
  "resBodyDesc": {
    "default": "successful operation with empty response body"
  }
}

*/

// ********RoostGPT********

import test, { expect, request } from "@playwright/test";
test("Logs out current logged in user session", async () => {
  const baseURL =  "https://petstore.swagger.io/v2";
  const context = await request.newContext({
    baseURL,
    extraHTTPHeaders: {
      "Content-Type": "application/json",
    },
  });

  const response = await context.get("/user/logout");
  
  if (response.status() === default) {
    expect(response.status()).toBe(default);
    console.log("Response for logoutUser is:", await response.json());
  }
})