// ********RoostGPT********
/*
Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o-standard

playwright test generated for endpoint: /store/order, with method: post
RoostTestHash={
  "paramDesc": {},
  "headerDesc": {},
  "reqBodyDesc": {
    "id": "integer",
    "petId": "integer",
    "quantity": "integer",
    "shipDate": "string",
    "status": "enum: placed, approved, delivered"
  },
  "resBodyDesc": {
    "200": "{\n  \"id\": \"integer\",\n  \"petId\": \"integer\",\n  \"quantity\": \"integer\",\n  \"shipDate\": \"string\",\n  \"status\": \"enum: placed, approved, delivered\"\n}",
    "400": "Invalid Order with empty response body"
  }
}

*/

// ********RoostGPT********

import test, { expect, request } from "@playwright/test";
import { readCsvData } from "./utility.js";

test("Place an order for a pet", async () => {
  const baseURL =  "https://petstore.swagger.io/v2";
  const context = await request.newContext({
    baseURL,
    extraHTTPHeaders: {
      "Content-Type": "application/json",
    },
  });

  const csvFilePath = `/var/tmp/Roost/RoostGPT/roost_test/1732294427/source/my-products/playwrightApiTests/tests/Place_an_order_for_a_pet.csv`
  const testData = await readCsvData(csvFilePath);

  for (let i = 0; i < testData.length; i++) {
    const csvDataRow = testData[i];
    const { statusCode, ...sampleData } = csvDataRow;

    const response = await context.post(`/store/order`, { data: JSON.stringify(sampleData) });
    expect(response.status()).toBe(statusCode);

    if (response.status() === statusCode) {
      console.log("Response for placeOrder is:", await response.json());
    }
  }
})