// ********RoostGPT********
/*
Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o-standard

playwright test generated for endpoint: /pet/{petId}/uploadImage, with method: post
RoostTestHash={
  "paramDesc": {
    "petId": "integer"
  },
  "headerDesc": {},
  "reqBodyDesc": {},
  "resBodyDesc": {
    "200": "{\n  \"code\": \"integer\",\n  \"type\": \"string\",\n  \"message\": \"string\"\n}"
  }
}

*/

// ********RoostGPT********

import test, { expect, request } from "@playwright/test";
import { readCsvData } from "./utility.js";

test("uploads an image", async () => {
  const baseURL =  "https://petstore.swagger.io/v2";
  const context = await request.newContext({
    baseURL,
    extraHTTPHeaders: {
      "Content-Type": "application/json",
    },
  });

  const csvFilePath = `/var/tmp/Roost/RoostGPT/roost_test/1732294427/source/my-products/playwrightApiTests/tests/uploads_an_image.csv`
  const testData = await readCsvData(csvFilePath);

  for (let i = 0; i < testData.length; i++) {
    const csvDataRow = testData[i];
    const { statusCode, ...sampleData } = csvDataRow;

    const response = await context.post(`/pet/${sampleData.petId}/uploadImage`);
    expect(response.status()).toBe(statusCode);

    if (response.status() === statusCode) {
      console.log("Response for uploadFile is:", await response.json());
    }
  }
})